### ISSUE TITLE
ebusd-esp does not reconnect to wifi

### ISSUE THREAD

**Issue by SebastianCornea** [john30/ebusd-esp#15]
HI John, 

I noticed random crashes of ebusd-esp. So far one that I can reproduce is when I restart the wifi access point or wifi is down for any reason and then back again, ebusd-esp will not reconnect to wifi or at least it's web config page is no longer available. Could be related to https://github.com/esp8266/Arduino/issues/4445 . 
I'm using the latest build 20181125.

**Comment by SebastianCornea** [comment]
Update: it actually reconnects to wifi just that it uses DHCP instead of preset IP address so it will listen on a different IP. If I reboot it from the web interface it will connect again correctly using the preset IP.

**Comment by john30** [comment]
do you have a power supply with enough amps? i know that Wemos is pretty unstable when the power supply is not good enough

**Comment by SebastianCornea** [comment]
Yes, more than it actually uses. For now I fixed the issue by setting a permanent IP address given in DHCP for the wemos MAC. 
The behavior is like it is forgetting all the settings as I noticed that the host name also resets to default. Could be a power fluctuation.

**Comment by john30** [comment]
not confirmed yet, thus reopening

**Comment by john30** [comment]
can you check with latest bin?

**Comment by SebastianCornea** [comment]
updated the firmware and disabled the DHCP fix. I couldn't reproduce the issue yet and I will keep it under observation for a while.

**Comment by john30** [comment]
great. I've just updated the binary again using the latest SoftwareSerial release which might also affect the behaviour in case other connectors than RX/TX are being used

**Comment by SebastianCornea** [comment]
So far the new version seems stable, no more wifi reconnect issues.

**Comment by john30** [comment]
good to know

**Comment by mozzarelka** [comment]
@john30, Thanks for update, so far no more connection issues. Less communication errors during normal work also.
