### ISSUE TITLE
No fix IP and no serial connection

### ISSUE THREAD

**Issue by find-a-good-nickname** [john30/ebusd-esp#16]
Dear John30,

I'm a newbie on ebusd, and tried to flash your mod'd firmware (20190407) to a Wemos D1 Mini. 
I accessed the flashed fw with a cellphone and configured the WiFi to the RasPi's WiFi. After a restart Wemos connected to the RasPi correctly, but when I tried to give a fix IP address, save it and reboot, the Wemos stayed on the DHCP'd IP, and not the fix. I tried to reflash and set the fix IP again and again, but the firmware can't save the IP. (There was ESPEasy and Tasmota on the Wemos before, and those were working flawlessly with a fix IP.)

Ok, I tried then to connect Wemos on USB with Putty, but it can't: the Putty window is empty with the COM port (I flashed Wemos through this port, so the virtual COM9 is WORKING) and with 115200 bps.

What can I do to give the fix IP to the Wemos/eBUS adapter 2.0?

Thanks for any ideas!

And an other bug: on the Configuration page there is a setting in the  3rd line: "gateway", but it contains really the netmask (255.255.255.0), not the WiFi gateway. If I write the real gateway in the box, and press Save & Reset, the Wemos isn't accessible at all and it can't connect to the WiFi.
![ebusd bin error]

The Configuration page is here (the "ebusd device string" is the IP that Wemos is on the WiFi. I tried to save and reset a few times, with that "3rd WIFI IP address" fix IP setting, but the IP isn't changed)
(https://user-images.githubusercontent.com/51930390/62709257-4eb32480-b9f5-11e9-857f-510a85dfa941.jpg)

**Comment by john30** [comment]
there were issues with DHCP as reported in #15, but those were fixed in the latest release.
if you configure for a fix IP you have to enter the gateway IP as well. Otherwise it might just fall back to DHCP.
If you connect via Putty, you have to press the reset button after the putty window is open. then a welcome message with intructions should appear.
btw: what device are you using exactly?

**Comment by find-a-good-nickname** [comment]
It is the latest release (20190407) and a Wemos D1 Mini.

Ah, thanks, I pressed the reset button when in Putty, and it welcomes to eBUS adapter 2.0 build 20190407, and shows IP (not fix) and WiFi signal. But when the "press return within 5 seconds to change the configuration" message appears, I press the Enter, the Wemos still writes "Entering eBUS mode" every time and nothing else. There is no menu or something.
![eBUSD putty Image1](https://user-images.githubusercontent.com/51930390/64513452-dfc53600-d2e8-11e9-8fbb-1613e7deba31.jpg)

And again: I wrote the gateway IP in the "gateway", but after a reboot the Wemos/eBUSD can't find and connect the WiFi. If I write the netmask (255.255.255.0) to the "gateway" it works well, connects to the WiFi in no time.  Look at the picture in my first message.
It seems that the "gateway" rubric is really the "netmask", and the real "gateway" is not visible at all.

**Comment by john30** [comment]
you probably have to adjust the putty settings wrt line separator.
for the gateway issue I can't verify your findings, it works perfectly well for me in all kinds of combinations

**Comment by john30** [comment]
please check again with the latest binary

**Comment by john30** [comment]
the DHCP issue might be solved with the latest binary from today. Please check again
