### ISSUE TITLE
support ESP32

### ISSUE THREAD

**Issue by john30** [john30/ebusd-esp#19]

**Comment by john30** [comment]
which esp32 board are you using @komw ?

**Comment by komw** [comment]
> which esp32 board are you using @komw ?

I'm using several different esp32.
currently I have a spare ESP32-CAM
I'm trying to use it instead of ESP8266, because with my heater it seems that latency with esp8266 is to high (with orangepi zero plus onboard UART, everything is ok).

**Comment by john30** [comment]
I've ordered an ESP32 now, will take some time for it to arrive

**Comment by komw** [comment]
Won't be better to publish source code to compile it by own?
