### ISSUE TITLE
Not possible to change TCP/IP...

### ISSUE THREAD

**Issue by darekhome** [john30/ebusd-esp#21]
Something is wrong? Or I'm doing something wrong?
I'm not able to change the TCP/IP - even I enter from 'putty' or from 'browser'
the address is not changing.
I want to change to '135' but the board is always appearing under '237'.

P.S. The board used: WEMOS D1 mini; today I specially purchased it as I had problems with mini PRO.

![ebus 2 tcp_ip](https://user-images.githubusercontent.com/55238173/70549714-f6dc2400-1b74-11ea-982d-fc48de430836.png)

**Comment by john30** [comment]
can you please try again with the latest binary as of bb20455 ?

**Comment by darekhome** [comment]
O.K. Now looks v. good. Checked.
One more question - why in the terminal the 'print-out' is not adjusted?
![2019-12-13 16_03_54-Window](https://user-images.githubusercontent.com/55238173/70809884-00f36200-1dc3-11ea-91e0-8192123aeab9.png)

**Comment by john30** [comment]
great.
you need to adjust the putty settings to have implicit cr in every lf and implicit lf in every cr
