### ISSUE TITLE
Sensor detected when Wemos connected by USB, but this state is not appearing in HTML GUI...

### ISSUE THREAD

**Issue by darekhome** [john30/ebusd-esp#22]
After 's' - connect Wi-Fi and reboot, no 'sensor' displayed at 'D4'.
Is that some bug?

`Enter your choice: s
Sensors:
D4: 288D3C94971203: temperature=23.69
1 sensors found
`

<img width="563" alt="sensor" src="https://user-images.githubusercontent.com/55238173/70855844-e3f98480-1ed1-11ea-94cd-bcaceefd2d69.png">

**Comment by darekhome** [comment]
Some update - when 'set-up' sensor with GUI and reboot - no sensor seen...
`{"sensors": []}`

<img width="553" alt="update" src="https://user-images.githubusercontent.com/55238173/70856076-e827a100-1ed5-11ea-8ad3-1d19b0549a76.png">

**Comment by john30** [comment]
the "s" is just for checking all ports for any connected sensor. you'd still have to set up the desired port as sensor port using "p" or "set initial" to sensor in HTML UI and then save and reboot to make it permanent

**Comment by darekhome** [comment]
O.K, but when we focus on HTML... I have initial situation - sensor connected to 'D5'.
<img width="556" alt="initial" src="https://user-images.githubusercontent.com/55238173/70861258-9e69a580-1f2b-11ea-87e2-a0d1fd73ed5b.png">

Set-up screen looks like above.

Then I click on at 'D5' 'Set Initial' 'Sensor' and then the 'Current' also is changing to 'Sensor'.
So screen looks like below:

<img width="563" alt="next" src="https://user-images.githubusercontent.com/55238173/70861272-ee486c80-1f2b-11ea-956d-293c82d80640.png">


Then I do 'Check & Update' and then 'Save & Reset'.

<img width="544" alt="reboot" src="https://user-images.githubusercontent.com/55238173/70861300-3a93ac80-1f2c-11ea-9192-bfe0c6cc92de.png">


After reboot I see:

<img width="559" alt="D5" src="https://user-images.githubusercontent.com/55238173/70861310-54cd8a80-1f2c-11ea-80d4-60234dde3cde.png">


But still no sensor at 'HTML'...

`{"sensors": []}`

**Comment by john30** [comment]
in your previous post the serial reported the sensors on D4

**Comment by darekhome** [comment]
Yes, I tried different pins, but result the same. Now it is at 'D5' - see proof.
And latest post - tested with D5.

![d5](https://user-images.githubusercontent.com/55238173/70863004-a2092680-1f43-11ea-963c-dff4773ebf6b.jpg)

**Comment by john30** [comment]
I'll try to reproduce at the weekend. Support for sensors is experimental anyway as stated in the readme

**Comment by darekhome** [comment]
Yes, I know... I'm aware of that. Thx...

**Comment by john30** [comment]
did you power the 1wire sensor appropriately?

**Comment by john30** [comment]
it works fine for me, also on D5. If you change the PIN in the HTML UI, the sensors appear immediately (and the sensors tab) if they were scanned successfully

**Comment by darekhome** [comment]
O.K. I'll check again. Also the supply of the sensor.
