### ISSUE TITLE
Not saved configuration in 'PRO' version...

### ISSUE THREAD

**Issue by darekhome** [john30/ebusd-esp#23]
I wanted to test 'PRO' version, but it is some problem with saving the configuration.
When I set-up with USB, all goes O.K. I.e. wi-fi is connecting.
<img width="483" alt="pro 1" src="https://user-images.githubusercontent.com/55238173/70863498-214d2900-1f49-11ea-99a8-c689e3889af3.png">

But when opening the page, doing some additional changes, etc. and then saving...

<img width="488" alt="pro 3" src="https://user-images.githubusercontent.com/55238173/70863537-8bfe6480-1f49-11ea-9a96-06e4746a495c.png">

After reboot it is not possible to connect with the IP defined.

<img width="240" alt="www" src="https://user-images.githubusercontent.com/55238173/70863634-60c84500-1f4a-11ea-9885-de3b4ff53e63.png">

But when (again) connecting via USB - the screen is initial, looks like no data saved...

<img width="491" alt="pro 4" src="https://user-images.githubusercontent.com/55238173/70863552-bbad6c80-1f49-11ea-9b49-987f1b4a56c1.png">

=================
Additional 'small-bug' on the initial screen 'host-name' is not updated, even if defined by user...
It is still default 'ebus-ct...'.
But on next screen it is O.K., given name by user 'ebus'.

<img width="335" alt="pro 2" src="https://user-images.githubusercontent.com/55238173/70863579-e1d30c80-1f49-11ea-8734-2e563e27c1d6.png">

<img width="388" alt="pro 10" src="https://user-images.githubusercontent.com/55238173/70863603-22328a80-1f4a-11ea-8405-057085711d40.png">

**Comment by john30** [comment]
both works fine for me, but I can't test on a pro as I don't own one

**Comment by blue-beard** [comment]
I confirm on the ebus-v2_d1mini_pro.bin firmware the wifi configuration is not saved, with other firmware the module starts at all for me. tried through serial and web interface
d1 mini from this order https://forum.fhem.de/index.php/topic,93190.0.html

**Comment by john30** [comment]
that should not be a "pro" version

**Comment by blue-beard** [comment]
> это не должно быть "про" версия

I understand, on the ESP8266MOD chip, but it starts only with pro firmware, several times yesterday I tried all the firmware in a circle
![IMG_20200130_094643](https://user-images.githubusercontent.com/18005139/73426805-53beb400-4346-11ea-812b-bafcf7501172.jpg)

**Comment by john30** [comment]
please post the output on serial after you flashed with the right firmware and rebooted

**Comment by blue-beard** [comment]
I apologize for the concern ebus-v2_d1mini.bin has earned and saves everything

**Comment by john30** [comment]
isse can be closed then I assume?
