### ISSUE TITLE
link to instructions for connecting to ebus?

### ISSUE THREAD

**Issue by perfectom** [john30/ebusd-esp#27]
Hi, this firmware looks great! Please is it possible to include links to instructions how to wire NodeMCU (and the other module types) ?  Just to complete the picture..  

 I have the firmware loaded on my nodemcu but I don't know how to wire it to my heater.  I understand it's possible to make a simple read-only ebus interface with these instructions:https://ebus-wiki.org/lib/exe/fetch.php/ebus/arduinoebus.pdf  Is it possible to use this with it?

Thank you 
Tom

**Comment by john30** [comment]
you can basically link it in several ways as the pins to be used are configurable to a certain extent. usually the RX+TX pins are used. wrt the interface you mentioned, I don't know if this works. just try.

**Comment by woutput** [comment]
I agree with @perfectom I also think this would make this (for me potentially) very useful repository even more useful.
@john30 would you be open to pull requests that would add this information to README.md for example?

**Comment by eiten** [comment]
Hello John30,

so https://easyeda.com/slavikb/EBus_Controller-26362750260a4f6baa63b59b5b35698d should work then as an interface, if we leave the LEDs away?

Regards, Edi

**Comment by john30** [comment]
I guess this should work, but you need to try

**Comment by vlad-323** [comment]
> Hello John30,
> 
> so https://easyeda.com/slavikb/EBus_Controller-26362750260a4f6baa63b59b5b35698d should work then as an interface, if we leave the LEDs away?
> 
> Regards, Edi

Hello. Maybe this is not actual, but this schematic is working, I repeated this adapter.

**Comment by john30** [comment]
> Hello. Maybe this is not actual, but this schematic is working, I repeated this adapter.

may be, but it is a very old design that consumes too much power from the eBUS. We have a [brand new design now](https://adapter.ebusd.eu/index.en) doing that a lot better
