### ISSUE TITLE
my -just received- Wemos D1 mini gives up after ebus adapter connection - power & flashing issue

### ISSUE THREAD

**Issue by netweaver1970** [john30/ebusd-esp#36]
Hi,
I just received my Ebus adapter v.3 with a pre-flashed Wemos D1 mini. It had a black-on-yellow 'esp3' Dymo label sticker on the ESP-12F module.

All good and fine, I could see the EBUS ssid, I connected to it, configured my home network ssid and password, rebooted, and it was nicely getting an IP address from my internal DHCP server.
Then I soldered the pinheaders on to allow it to marry it to the EBUS adapter itself.
From that moment, after inserting into the EBUS adapter and removing the Wemos from the adapter, the pre-flashed firmware was always rebooting, due to watchdog timer kicking in, bootmode (3,6).
Whatever I tried. reset, unplug/plug the usb, nothing helped. I could see the short flash every x seconds and I saw the same wdt reboot message on serial port over and over.

Then i tried to reflash using both the nodemcu flasher AND the esptool flasher, both as per instructions, using the downloaded ebus-v3-d1mini.bin file. Same effect. Reboots of the Wemos d1 mini.

I though it was maybe broken, so I decided to try something else. I quickly took an arduino blinky example from/in PlatformIO, flashed it to the board, and look, it worked fine. Nice -stupid- blinky.
I tried again putting the official firmware on it using both tools ... wdt timer kicking in again.

Then, almost desperate, I tried the 'official' Espressif flasher, downloaded from their website. And see, when flashing the same bin file as I've done about 10x before, this time it worked. It has 'properly' written the firmware file, reset the config and I see the default EBUS ssid back.

I stuck the soldered Wemos module on the EBUS Adapter, re-plugged in the usb cable and guess what, adapter orange and green led full on, blue led flashing, NO fast Wemos blue led flashing and no EBUS ssid anymore. Deja-vu feeling ...

Take it off the adapter ... try again ... luckily the EBUS ssid is back.
So i start to suspect the laptop USB power port I use for setting up. And indeed, when connecting to a USB powerbank, the Wemos d1 mini inserted IN the EBUS adapter nicely work together and I still have the EBUS ssid.

I can continue... Just lost a few hours :)

I just wrote this so it can be found (when asking our good Friend) if other people might have similar issues. And maybe so you can can update the documentation, also indicate the need to supply a more than decent amount of mA otherwise funny things can happen, requiring some unexpected tinkering. And maybe give the Espressive tool some well deserved mention, as for some reason, the other tools didn't reflash the firmware back correctly.

Cheers.

**Comment by john30** [comment]
I guess the issue does not have anything to do with the flasher then, just a power supply issue after all
