### ISSUE TITLE
Wemos D1 and esera coupler usb

### ISSUE THREAD

**Issue by foudezic63** [john30/ebusd-esp#39]
Hello,

Need help :)
I am struggling to capture if I can plug the wemos D1 mini with the esera ebus coupler through the mini USB port. If yes, which configuration should I use ?

Thanks !

**Comment by HeikoGr** [comment]
I don‘t think that this is working. The mini usb port is - as far as i know - not capable of acting as an usb host.

**Comment by john30** [comment]
exactly, it can't be done that way. you'd have to open the coupler and remove the USB interface part to replace that with the wemos

**Comment by foudezic63** [comment]
Ok thanks :)
I'll change my configuration to plug the coupler directly to my raspb4 then.
Thank you for your quick answers !
