### ISSUE TITLE
ebusd Docker Multi-arch support includes linux/arm* platforms?

### ISSUE THREAD

**Issue by netweaver1970** [john30/ebusd-esp#42]
Hi,
when trying to do a docker pull, as per your instructions, on my 64bit Raspberry but whatever I try, I'm getting an image for linux/amd64 architecture served. Is the auto multi-arch selection working fine? Are the other achitectures uploaded?
  ![image](https://user-images.githubusercontent.com/18028618/115858596-72b7d300-a42f-11eb-83a5-948070f25bbd.png)

actually, my platform as per uname -m is:
![image](https://user-images.githubusercontent.com/18028618/115860488-dba04a80-a431-11eb-85bf-bd7a50bc3415.png)

Then, when trying to specify the specific platform to pull (hard-coded) on the docker run command line, I'm getting the same error:
  ![image](https://user-images.githubusercontent.com/18028618/115859940-19e93a00-a431-11eb-8b1b-40b88ddfdf93.png)

Also with arm64v8 as platform:
![image](https://user-images.githubusercontent.com/18028618/115861364-ffb05b80-a432-11eb-8cac-b2f710b3f059.png)

also with the linux/arm32v7 platform:
![image](https://user-images.githubusercontent.com/18028618/115861788-87966580-a433-11eb-95ab-53cd50395ac8.png)

Are the linux/arm* architectures missing or am I doing something wrong?
Can you provide, in case not provided or help further? All my other containers on this box are fine, no single issue with architectures so I feel it must be an EBUSD image issue.

Also, can you provide some examples for docker-compose usage? 
It might save time later for people wanting to implement. 
I started with it but I could not verify it yet since I can't even get the base use-case (with docker run) working due to the missing image for my architecture.

```version: '2'
services:
#  ebusd:
#    container_name: ebusd
#    image: john30/ebusd
#    restart: unless-stopped
#    ports:
#      - "8888"
#    volumes:
#      - ./volumes/ebusd/data:/data
#    command: -f --scanconfig --mqttport=1883 --mqtthost=192.168.0.11 --mqttuser=ebusd -d enh:192.168.0.128:9999
```

Thanks.

**Comment by john30** [comment]
wron repo
