### ISSUE TITLE
Error: invalid WIFI secret

### ISSUE THREAD

**Issue by 6Xkljk8Vj7Tk1k4** [john30/ebusd-esp#48]
Hi,

I have a dedicated ssid for my iot devices where all works fine. However for this one I cannot save wifi password (64 characters):
![image](https://user-images.githubusercontent.com/754027/131288237-11ced27c-36b6-495c-84b6-14941d6a525c.png)

Its the same for serial configuration

Any ideas?

**Comment by john30** [comment]
the password field should accept 64 characters max. are you sure it isn't longer?
