### ISSUE TITLE
no eBUS signal with Protherm Skat

### ISSUE THREAD

**Issue by hryamzik** [john30/ebusd-esp#49]
Hardware:

`NodeMcu v1.0`
`Protherm Skat 9`

Using all the defaults and RX/TX pins I get the following status:

```
Chip ID: 007a55a0
Hostname: ebus-7a55a0
Up time: 72
Free heap: 34736
ebusd connected: no
eBUS signal: no signal
eBUS initial signal: echo
```

And heater fails to `f.49` error, according to manuals description is `Short circuit on the eBus, overload on the eBus or on the eBus 2 of a voltage source with different polarity`.

Any ideas how to debug this?

**UPD:** I've just found a note that voltage on EBUS should be 15-24 Volts, not sure how to properly archive this.
**UPD:** Looks like I miss the ebus adapter, it wasn't clear for me that ESP can't drive the bus directly.

**Comment by john30** [comment]
yes, you need an [adapter like this](https://adapter.ebusd.eu/index.en.html) to gain access to the bus signal

**Comment by hryamzik** [comment]
Thanks, I've already placed my order!
