### ISSUE TITLE
Feature: Include the current build type, with the link to download the firmware

### ISSUE THREAD

**Issue by LordMike** [john30/ebusd-esp#52]
When I revisit my ebus esp once in a while, I can't remember if its the D1 Pro, D1 Lite or what..

Could you include the current build type, on the HTML page?

You've added a link to this github repo - and that's awesome :)

**Comment by john30** [comment]
you can see that as well in the HTTP UI with "?verbose" as query

**Comment by LordMike** [comment]
Oh - I see.. Could you then add a link at the bottom of the page with "more details" ? :)

**Comment by john30** [comment]
done with next revision
