### ISSUE TITLE
Work`s without adapter?

### ISSUE THREAD

**Issue by mefisto22** [john30/ebusd-esp#62]
Can i use tihs firmware with ESP32 to read my gas boiler ebus datas? Or i must to order an adapter for esp32?

**Comment by mfalkvidd** [comment]
Is the adapter required for esp8266 as well? I have read the readme, but can't figure out if this can be used standalone or if the adapter is required.

**Comment by john30** [comment]
you can't just connect any ESP directly to a bus system with completely different voltage level (24V). so answer is: an adapter is always needed
