### ISSUE TITLE
Question: is it possible to use Serial-to-TCP-Bridge implemented in Tasmota ?

### ISSUE THREAD

**Issue by kofec** [john30/ebusd-esp#82]
Does any one know/try if is it possible to use Serial-to-TCP-Bridge implemented in Tasmota ?
If so what should we set for TCPBaudRate :
TCPBaudRate <x>: sets the baud rate for serial (only 8N1 mode), min 1200, max 115200 by 1200 increments.
https://tasmota.github.io/docs/Serial-to-TCP-Bridge/
As I understand it should be OK: set GPIO1 as TCP Tx and GPIO3 as TCP Rx.
And port set to: 9999

**Comment by john30** [comment]
I tried that quite some time ago and it works in principle but not very reliable
