### ISSUE TITLE
which dist to flash to ebusAdapter V5?

### ISSUE THREAD

**Issue by AlexKid007** [john30/ebusd-esp#83]
I'm trying to flash my new ebus Adapter V5 but I'm not really sure which *.bin to use. I tried a lot but after flashing via ESPHome and a restart I only get the following 
`ESP-ROM:esp32c3-api1-20210207
Build:Feb  7 2021
rst:0x7 (TG0WDT_SYS_RST),boot:0xd (SPI_FAST_FLASH_BOOT)
Saved PC:0x40047ed2
Invalid chip id. Expected 5 read 3460. Bootloader for wrong chip?
ets_main.c 333 `

**Comment by john30** [comment]
just follow the [manual](https://adapter.ebusd.eu/v5/steps.en).
wrong repo anyway

**Comment by AlexKid007** [comment]
Sorry my fault thought the embedded ESP Web tool is a Picture. 🫣
