### ISSUE TITLE
EBUS AP not disabled after configuring WiFi Client/Station

### ISSUE THREAD

**Issue by dakaix** [john30/ebusd-esp#84]
I have just setup my eBUS Adapter v5 (20230618) and successfully connected it to my home WiFi network. However after doing this the "EBUS" access point is not disabled, and (unless I missed it!) there doesn't seem to be a way to do so. 

If I enable the "Access Point" setting, and configure a network name & password I can (at least) replace the open EBUS network, but I would prefer to disable any access point from being broadcast.

**Comment by john30** [comment]
wrong repo, see ebusd-esp32
