### ISSUE TITLE
Open source firmware

### ISSUE THREAD

**Issue by louiecaulfield** [john30/ebusd-esp#85]
Sorry if this question has been asked (and answered) elsewhere before - I couldn't find it.

Are there any plans to open source the firmware running on the ebus adapter?

I just received my V5 and would love to go hacking about :-)

**Comment by BartoszKordylewski** [comment]
Yup, me too - I would love to somehow connect it with SUPLA system, SUPLA has integration with Arduino (ESP etc.), but for eBUS there is nothing to just take and edit...

**Comment by john30** [comment]
duplicate of #5
