### ISSUE TITLE
No ebus signal

### ISSUE THREAD

**Issue by Tabtaste** [john30/ebusd-esp#86]
Hey, on witch pin I should put on the ebus ? I Use a esp8622 nodemcu V3 

And witch rx tx setting should I Use? 

Greetings

**Comment by kmlZ** [comment]
> Hey, on witch pin I should put on the ebus ? I Use a esp8622 nodemcu V3
> 
> And witch rx tx setting should I Use?
> 
> Greetings

Have you maganed to establish connection?

**Comment by john30** [comment]
it is shown in the web+repl which GPIOs it is
