### ISSUE TITLE
Feature request: firmware-local message repeats

### ISSUE THREAD

**Issue by bobrippling** [john30/ebusd-esp#89]
I've been interested for some time in being able to control my boiler using ebusd. This is possible using messages such as the `SetModeOverride`.

### Problem

With these messages, the boiler [expects an update every 10 minutes](https://github.com/john30/ebusd/issues/179#issuecomment-1883139775) ([source](https://old.reddit.com/r/homeassistant/comments/ylty4u/ebus_thermostat_controls_with_modulation/j3bq2td/?context=3)) on `SetMode`, otherwise it resets to default.

My concern is that my boiler must have its heating set to constant/on, and then rely on these messages every 10 minutes to turn it off when I don't want to use it. If there was an issue with ebusd or the host on which ebusd runs, the boiler would run away with the heating on.

### Feature

What are your thoughts on a feature where the firmware can repeat a message by itself, without an active ebusd connection? This could then be configured once by ebusd, so if ebusd terminated or the host otherwise crashed, the ebus adapter would be able to maintain the boiler by repeating this message every 10 minutes.

------

### SetMode summary

(mostly notes for myself / anyone interested)

<details>
<summary>SetModeOverride</summary>

Using this as a summary of all the discussions I've found to be useful:
- john30/ebusd#179
  - Specifically these comments:
    - The message: https://github.com/john30/ebusd/issues/179#issuecomment-434628658
    - Scripting: https://github.com/john30/ebusd-configuration/issues/242#issuecomment-1194481837
    - Details on parameters: https://github.com/john30/ebusd-configuration/issues/242#issuecomment-1507692520
- john30/ebusd#190
- john30/ebusd#170
- john30/ebusd-configuration#220
- john30/ebusd-configuration#114
- john30/ebusd#364

And possibly for circulation pumps too (john30/ebusd-configuration#135).

which, to summarise here for anyone else wanting to do the same, we can use to make these messages writable (assuming your boiler accepts them):
- `SetMode` (above links)
- john30/ebusd-configuration#78 and https://github.com/john30/ebusd-configuration/issues/120#issuecomment-1379747064
  - `FlowsetHcMax`
  - `SetTempdesired`

While these [don't seem to be writable](https://github.com/john30/ebusd-configuration/issues/114#issuecomment-437898932):
- `HwcTempDesired`
- `FlowTempDesired`

There are other messages we're not sure about, which we may be able to configure too:
- john30/ebusd-configuration#111
- john30/ebusd-configuration#78 (hex command found for controlling boiler)

</details>

<details>
<summary>HomeAssistant / MQTT setup</summary>

- https://github.com/john30/ebusd-configuration/issues/170#issuecomment-709592197
- https://github.com/john30/ebusd/issues/214
- https://github.com/john30/ebusd/issues/211
- https://github.com/john30/ebusd/discussions/828#discussion-4817256
</details>

**Comment by john30** [comment]
development on this firmware is no longer continued.
instead, using a [Wemos C3 mini](https://www.wemos.cc/en/latest/c3/c3_mini.html) with the [special build of the V5 adapter firmware](https://adapter.ebusd.eu/v5/wemos.en) can easily be used as replacement
